---
- name: strategy serial 1, 4, 5
  hosts: group1
  order: reverse_inventory
  serial:
    - 1 
    - 4
    - 5
  tasks:
    - name: task1
      ansible.builtin.command: /bin/sleep 1
    - name: task2
      ansible.builtin.command: /bin/sleep 1
    - name: task3
      ansible.builtin.command: /bin/sleep 1
